package main

import (
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const genSpecDoc = `
updaters:
  - name: updater
    source: {backend: github, owner: a, repo: b}
    apply: {backend: self, base_dir: $BASE_DIR}
config:
  core:
    url_test_url: {type: string, default: "http://cp.cloudflare.com/generate_204", control: text}
    log:
      level: {type: string, default: error, control: select, options: [debug, info, warn, error]}
    traffic_graph_history: {type: int, default: 60, control: select, options: [30, 60, 120, 300]}
  log:
    limit: {type: int, default: 100, control: number, min: 10}
  plugins:
    enabled: {type: bool, default: false, disabled: true}
  privileges:
    setcap: {control: action, action: setcap, confirm: true, platforms: [linux]}
`

func TestRunGeneratesAccessor(t *testing.T) {
	dir := t.TempDir()
	specPath := filepath.Join(dir, "project.yaml")
	outPath := filepath.Join(dir, "accessor.go")
	if err := os.WriteFile(specPath, []byte(genSpecDoc), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := run(specPath, outPath, "appconfig"); err != nil {
		t.Fatalf("run: %v", err)
	}
	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatal(err)
	}
	src := string(data)
	if !strings.Contains(src, "// Code generated by projectspec-gen; DO NOT EDIT.") {
		t.Errorf("generated source missing header:\n%s", src)
	}
	// gofmt aligns struct fields with padding; match against a
	// whitespace-collapsed copy.
	squashed := strings.Join(strings.Fields(src), " ")
	for _, want := range []string{
		"package appconfig",
		`import fwconfig "github.com/he11ah0und/config"`,
		"type Accessor struct",
		"Core *CoreAccessor",
		"Log *LogAccessor",
		"Plugins *PluginsAccessor",
		"type CoreAccessor struct",
		"URLTestURL *fwconfig.Cell",
		"TrafficGraphHistory *fwconfig.Cell",
		"Log *CoreLogAccessor",
		"type CoreLogAccessor struct",
		"Level *fwconfig.Cell",
		"func NewAccessor(sheet *fwconfig.Sheet) *Accessor",
		`URLTestURL: sheet.MustGet("core", "url_test_url"),`,
		`Level: sheet.MustGet("core", "log", "level"),`,
		`TrafficGraphHistory: sheet.MustGet("core", "traffic_graph_history"),`,
		`Limit: sheet.MustGet("log", "limit"),`,
		`Enabled: sheet.MustGet("plugins", "enabled"),`,
	} {
		if !strings.Contains(squashed, want) {
			t.Errorf("generated source missing %q:\n%s", want, src)
		}
	}
	// The output is already gofmt-formatted: re-formatting is a no-op.
	formatted, err := format.Source(data)
	if err != nil {
		t.Fatalf("generated source does not parse: %v", err)
	}
	if string(formatted) != src {
		t.Errorf("generated source is not gofmt-stable")
	}
	// Action entries carry no Sheet cell, so they must not appear.
	for _, unwanted := range []string{"Privileges", "Setcap", `MustGet("privileges"`} {
		if strings.Contains(src, unwanted) {
			t.Errorf("generated source contains action entry artifact %q:\n%s", unwanted, src)
		}
	}
}

func TestRunRequiresFlags(t *testing.T) {
	for _, args := range [][3]string{
		{"", "out.go", "pkg"},
		{"spec.yaml", "", "pkg"},
		{"spec.yaml", "out.go", ""},
	} {
		if err := run(args[0], args[1], args[2]); err == nil {
			t.Errorf("run(%q, %q, %q): want error", args[0], args[1], args[2])
		}
	}
}

func TestGoName(t *testing.T) {
	cases := map[string]string{
		"url_test_url":    "URLTestURL",
		"theme_mode":      "ThemeMode",
		"auto_check_self": "AutoCheckSelf",
		"ui_scale":        "UIScale",
		"server_id":       "ServerID",
		"api_endpoint":    "APIEndpoint",
	}
	for seg, want := range cases {
		if got := goName(seg); got != want {
			t.Errorf("goName(%q): want %s, got %s", seg, want, got)
		}
	}
}
