// Command projectspec-gen generates a typed config accessor from a
// project.yaml spec: a live facade over a *fwconfig.Sheet with one cell
// field per config entry.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"

	"github.com/he11ah0und/projectspec"
)

func main() {
	specPath := flag.String("spec", "", "path to project.yaml (required)")
	outPath := flag.String("out", "", "path of the generated .go file (required)")
	pkg := flag.String("pkg", "", "package name of the generated file (required)")
	flag.Parse()
	if err := run(*specPath, *outPath, *pkg); err != nil {
		fmt.Fprintln(os.Stderr, "projectspec-gen:", err)
		os.Exit(1)
	}
}

func run(specPath, outPath, pkg string) error {
	if specPath == "" {
		return fmt.Errorf("-spec is required")
	}
	if outPath == "" {
		return fmt.Errorf("-out is required")
	}
	if pkg == "" {
		return fmt.Errorf("-pkg is required")
	}
	data, err := os.ReadFile(specPath)
	if err != nil {
		return fmt.Errorf("read spec: %w", err)
	}
	// The config section uses no placeholders; BASE_DIR/DATA_DIR stand in so
	// an updaters section with tokens still validates.
	spec, err := projectspec.Load(data, projectspec.Vars{"BASE_DIR": "x", "DATA_DIR": "x"})
	if err != nil {
		return err
	}
	src, err := generate(pkg, spec.Config)
	if err != nil {
		return err
	}
	if err := os.WriteFile(outPath, src, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	return nil
}

// configNode is one node of the config tree rebuilt from the flattened
// entries: either a leaf (a setting) or a section with ordered children.
type configNode struct {
	seg      string
	path     []string
	leaf     bool
	children []*configNode
	bySeg    map[string]*configNode
}

// buildTree rebuilds the section hierarchy from flattened entries, keeping
// spec order.
func buildTree(entries []projectspec.ConfigEntry) *configNode {
	root := &configNode{bySeg: map[string]*configNode{}}
	for _, e := range entries {
		cur := root
		for _, seg := range e.Path {
			child, ok := cur.bySeg[seg]
			if !ok {
				child = &configNode{
					seg:   seg,
					path:  append(append([]string{}, cur.path...), seg),
					bySeg: map[string]*configNode{},
				}
				cur.bySeg[seg] = child
				cur.children = append(cur.children, child)
			}
			cur = child
		}
		cur.leaf = true
	}
	return root
}

// initialisms are rendered all-caps in Go names.
var initialisms = map[string]bool{"URL": true, "UI": true, "ID": true, "API": true}

// goName converts a snake_case path segment to a Go-idiomatic CamelCase name
// (e.g. url_test_url -> URLTestURL).
func goName(seg string) string {
	var b strings.Builder
	for _, part := range strings.Split(seg, "_") {
		if part == "" {
			continue
		}
		if up := strings.ToUpper(part); initialisms[up] {
			b.WriteString(up)
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(part[1:])
	}
	return b.String()
}

// typeName is the accessor struct name for a node path: concatenated
// CamelCase segments + "Accessor".
func typeName(path []string) string {
	var b strings.Builder
	for _, seg := range path {
		b.WriteString(goName(seg))
	}
	b.WriteString("Accessor")
	return b.String()
}

// generate renders the accessor source for the given config entries and
// gofmt-formats it.
func generate(pkg string, entries []projectspec.ConfigEntry) ([]byte, error) {
	root := buildTree(entries)
	var b bytes.Buffer
	b.WriteString("// Code generated by projectspec-gen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("import fwconfig \"github.com/he11ah0und/config\"\n\n")
	emitStruct(&b, root)
	b.WriteString("\n// NewAccessor binds the accessor tree to sheet.\n")
	b.WriteString("func NewAccessor(sheet *fwconfig.Sheet) *Accessor {\n\treturn ")
	emitLiteral(&b, root, 1)
	b.WriteString("\n}\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return src, nil
}

// emitStruct writes the struct declaration for node and, after it, the
// declarations of its child sections.
func emitStruct(b *bytes.Buffer, node *configNode) {
	if len(node.path) == 0 {
		b.WriteString("// Accessor is a typed, live facade over a *fwconfig.Sheet: every\n")
		b.WriteString("// field is a cell handle, so reads and writes through the accessor go\n")
		b.WriteString("// straight to the sheet and stay in sync with the rest of the app.\n")
	}
	fmt.Fprintf(b, "type %s struct {\n", typeName(node.path))
	for _, c := range node.children {
		if c.leaf {
			fmt.Fprintf(b, "\t%s *fwconfig.Cell\n", goName(c.seg))
		} else {
			fmt.Fprintf(b, "\t%s *%s\n", goName(c.seg), typeName(c.path))
		}
	}
	b.WriteString("}\n")
	for _, c := range node.children {
		if !c.leaf {
			b.WriteString("\n")
			emitStruct(b, c)
		}
	}
}

// emitLiteral writes the composite literal binding node to sheet cells.
func emitLiteral(b *bytes.Buffer, node *configNode, depth int) {
	pad := strings.Repeat("\t", depth)
	fmt.Fprintf(b, "&%s{\n", typeName(node.path))
	for _, c := range node.children {
		fmt.Fprintf(b, "%s%s: ", pad, goName(c.seg))
		if c.leaf {
			args := make([]string, len(c.path))
			for i, seg := range c.path {
				args[i] = fmt.Sprintf("%q", seg)
			}
			fmt.Fprintf(b, "sheet.MustGet(%s),\n", strings.Join(args, ", "))
		} else {
			emitLiteral(b, c, depth+1)
			b.WriteString(",\n")
		}
	}
	fmt.Fprintf(b, "%s}", strings.Repeat("\t", depth-1))
}
